spring:
  application:
    name: discovery
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost
